GET http://localhost:3000/persons


###
POST http://localhost:3000/add-person
Content-type: application/json

{
  "type": "user",
  "vote": 1,
  "name": "Faranak",
  "age": 25,
  "password": "65465466646"
}


###

POST http://localhost:3000/login
Content-type: application/json

{
    "name": "shahab",
    "password":"135966"
}


###
GET http://localhost:3000/zahremar/shahabi
